//! CLI entry. `cargo run` prints all four personas plus the allergy demo.
//!
//! ```text
//! cargo run
//! cargo run -- --persona A
//! cargo run -- --persona A --allergy ashwagandha
//! cargo run -- --demo-allergy
//! cargo run -- --write-outputs
//! ```

use std::env;
use std::fs;
use std::path::Path;

use cld9_engine::engine::{allergy_demo, recommend};
use cld9_engine::persona::{all_personas, persona_by_id};
use cld9_engine::report::{
    banner, render_allergy_demo, render_allergy_demo_md, render_cli, render_markdown,
};

fn main() {
    let args: Vec<String> = env::args().skip(1).collect();
    if args.iter().any(|a| a == "--help" || a == "-h") {
        print_help();
        return;
    }

    if args.iter().any(|a| a == "--tui") {
        cld9_engine::tui::run().expect("tui session");
        return;
    }

    let write = args.iter().any(|a| a == "--write-outputs");
    let demo = args.iter().any(|a| a == "--demo-allergy");
    let persona_id = arg_value(&args, "--persona");
    let allergies = arg_values(&args, "--allergy");

    println!("{}\n", banner());

    if demo {
        run_allergy_demos(write);
        return;
    }

    if let Some(id) = persona_id {
        match persona_by_id(&id) {
            Some(p) => {
                let p = if allergies.is_empty() {
                    p
                } else {
                    let extra: Vec<&str> = allergies.iter().map(String::as_str).collect();
                    p.with_allergies(&extra)
                };
                let rec = recommend(&p);
                print!("{}", render_cli(&rec));
                if write {
                    write_outputs(&[rec], true);
                }
            }
            None => {
                eprintln!("Unknown persona `{id}`. Use A, B, C, or K (see README).");
                std::process::exit(1);
            }
        }
        return;
    }

    let recs: Vec<_> = all_personas().iter().map(recommend).collect();
    for rec in &recs {
        print!("{}", render_cli(rec));
    }
    run_allergy_demos(false);
    if write {
        write_outputs(&recs, true);
    }
}

fn run_allergy_demos(write: bool) {
    let a = cld9_engine::persona::persona_a();
    let c = cld9_engine::persona::persona_c();

    let (a0, a1) = allergy_demo(&a, &["ashwagandha"]);
    print!(
        "{}",
        render_allergy_demo("Persona A", &["ashwagandha"], &a0, &a1)
    );

    let (c0, c1) = allergy_demo(&c, &["caffeine"]);
    print!(
        "{}",
        render_allergy_demo("Persona C", &["caffeine"], &c0, &c1)
    );

    if write {
        let dir = Path::new("outputs");
        let _ = fs::create_dir_all(dir);
        let mut md = String::new();
        md.push_str(&render_allergy_demo_md(
            "Persona A",
            &["ashwagandha"],
            &a0,
            &a1,
        ));
        md.push('\n');
        md.push_str(&render_allergy_demo_md(
            "Persona C",
            &["caffeine"],
            &c0,
            &c1,
        ));
        fs::write(dir.join("allergy_demo.md"), md).expect("write allergy_demo.md");
        println!("Wrote outputs/allergy_demo.md");
    }
}

fn write_outputs(recs: &[cld9_engine::Recommendation], also_demo: bool) {
    let dir = Path::new("outputs");
    fs::create_dir_all(dir).expect("outputs/");

    let mut all = String::new();
    all.push_str("# CLD-9-style engine — sample outputs\n\n");
    all.push_str("Generated by `cargo run -- --write-outputs`.\n\n");
    all.push_str(&format!("{}\n\n", banner()));

    for rec in recs {
        let name = format!("persona_{}.md", rec.persona_id.to_lowercase());
        let body = render_markdown(rec);
        fs::write(dir.join(&name), &body).expect("write persona file");
        println!("Wrote outputs/{name}");
        all.push_str(&body);
        all.push_str("\n---\n\n");
    }

    if also_demo {
        let a = cld9_engine::persona::persona_a();
        let c = cld9_engine::persona::persona_c();
        let (a0, a1) = allergy_demo(&a, &["ashwagandha"]);
        let (c0, c1) = allergy_demo(&c, &["caffeine"]);
        let demo = format!(
            "{}\n{}\n",
            render_allergy_demo_md("Persona A", &["ashwagandha"], &a0, &a1),
            render_allergy_demo_md("Persona C", &["caffeine"], &c0, &c1)
        );
        fs::write(dir.join("allergy_demo.md"), &demo).expect("write allergy_demo.md");
        println!("Wrote outputs/allergy_demo.md");
        all.push_str(&demo);
    }

    fs::write(dir.join("results.md"), all).expect("write results.md");
    println!("Wrote outputs/results.md");
}

fn arg_value(args: &[String], flag: &str) -> Option<String> {
    args.windows(2).find(|w| w[0] == flag).map(|w| w[1].clone())
}

fn arg_values(args: &[String], flag: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut i = 0;
    while i < args.len() {
        if args[i] == flag {
            if let Some(v) = args.get(i + 1) {
                out.push(v.clone());
                i += 2;
                continue;
            }
        }
        i += 1;
    }
    out
}

fn print_help() {
    println!(
        "\
{}

USAGE:
  cargo run
  cargo run --release
  cargo run -- --persona A
  cargo run -- --persona A --allergy ashwagandha
  cargo run -- --persona C --allergy caffeine
  cargo run -- --demo-allergy
  cargo run -- --write-outputs
  cargo run -- --tui

Personas: A, B, C, K
",
        banner()
    );
}
